"""Hidden one-pass memory update protocol.

The visible answer and the memory proposal are generated by one model call.
The streaming filter withholds the protocol marker across arbitrary chunk
boundaries, so internal JSON never appears in the cockpit.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from typing import Any

from memory_store import MemoryStore


OPEN_MARKER = "<MEMORY_UPDATE>"
CLOSE_MARKER = "</MEMORY_UPDATE>"

PERSONAL_KINDS = {
    "user_fact",
    "user_preference",
    "user_goal",
    "relationship_context",
    "health_context",
    "personal_context",
}


MEMORY_PROTOCOL_INSTRUCTIONS = f"""
[INTERNAL MEMORY DELTA PROTOCOL]
Only when this turn creates or changes a durable fact, preference, goal,
decision, project state, or unresolved task, append one compact private block
after the complete user-visible answer:
{OPEN_MARKER}
{{
  "memories": [
    {{
      "operation": "upsert",
      "kind": "user_fact|user_preference|user_goal|project_fact|decision|health_context",
      "key": "short_stable_key",
      "value": "one concise durable fact",
      "confidence": 0.0,
      "salience": 0.0,
      "explicitly_stated": true,
      "sensitive": false,
      "source_urls": [],
      "freshness_days": 30
    }}
  ],
  "session": {{}}
}}
{CLOSE_MARKER}
Rules:
- If nothing durable changed, end immediately after the visible answer and emit no private block.
- Include only changed session fields. Never repeat the whole session checkpoint.
- Valid session fields are title, summary, current_task, open_loops, decisions, tone_state, and active_project.
- The private block must be valid JSON, never Markdown, and must be the final output.
- Keep values concise. Omit memories or session when that section has no change.
- Personal and sensitive memories require an explicit user statement.
- Never infer or store a diagnosis. Health context must remain an explicit self-report.
- Do not turn transient moods into durable identity facts. Explicit wellbeing self-reports are captured separately by the controller-owned private timeline.
- Do not store greetings, guesses, passwords, credentials, secret tokens, or raw code.
- A world_fact or hard_fact requires provided web evidence and must list one or more exact Source URLs from it.
- Give volatile facts a short freshness_days value; use longer values only for genuinely stable facts.
""".strip()


@dataclass
class FilterResult:
    visible: str = ""
    hidden: str = ""


class HiddenMemoryFilter:
    """Separates a trailing memory block without leaking split markers."""

    def __init__(self, hidden_limit: int = 32768):
        self._pending = ""
        self._hidden_parts: list[str] = []
        self._state = "visible"
        self._hidden_limit = hidden_limit

    def feed(self, chunk: str) -> str:
        if not chunk:
            return ""
        self._pending += chunk
        if self._state == "done":
            self._pending = ""
            return ""

        if self._state == "visible":
            marker_at = self._pending.find(OPEN_MARKER)
            if marker_at >= 0:
                visible = self._pending[:marker_at]
                self._pending = self._pending[marker_at + len(OPEN_MARKER):]
                self._state = "hidden"
                self._consume_hidden()
                return visible
            keep = len(OPEN_MARKER) - 1
            if len(self._pending) <= keep:
                return ""
            visible = self._pending[:-keep]
            self._pending = self._pending[-keep:]
            return visible

        self._consume_hidden()
        return ""

    def _consume_hidden(self) -> None:
        close_at = self._pending.find(CLOSE_MARKER)
        if close_at >= 0:
            self._append_hidden(self._pending[:close_at])
            self._pending = ""
            self._state = "done"
            return
        keep = len(CLOSE_MARKER) - 1
        if len(self._pending) > keep:
            self._append_hidden(self._pending[:-keep])
            self._pending = self._pending[-keep:]

    def _append_hidden(self, text: str) -> None:
        current = sum(len(part) for part in self._hidden_parts)
        if current >= self._hidden_limit:
            return
        self._hidden_parts.append(text[: self._hidden_limit - current])

    def finish(self) -> FilterResult:
        visible = ""
        if self._state == "visible":
            visible = self._pending
        elif self._state == "hidden":
            self._append_hidden(self._pending)
        self._pending = ""
        return FilterResult(visible=visible, hidden="".join(self._hidden_parts).strip())


def parse_memory_payload(raw: str) -> dict[str, Any] | None:
    if not raw.strip():
        return None
    cleaned = raw.strip()
    cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"\s*```$", "", cleaned)
    start = cleaned.find("{")
    end = cleaned.rfind("}")
    if start < 0 or end <= start:
        return None
    try:
        payload = json.loads(cleaned[start:end + 1])
    except (json.JSONDecodeError, TypeError):
        return None
    return payload if isinstance(payload, dict) else None


def _as_bool(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)):
        return value != 0
    if isinstance(value, str):
        return value.strip().casefold() in {"1", "true", "yes", "on"}
    return False


def _evidence_urls(evidence: str) -> set[str]:
    urls = re.findall(r"https?://[^\s<>\"]+", evidence)
    return {url.rstrip(".,;:!?)]}'\"") for url in urls}


def apply_memory_payload(
    store: MemoryStore,
    payload: dict[str, Any] | None,
    *,
    session_id: str,
    source_message_id: int,
    grounded_evidence: str = "",
) -> dict[str, int]:
    result = {"stored": 0, "skipped": 0, "session_updated": 0}
    if not payload:
        return result

    memories = payload.get("memories", [])
    if isinstance(memories, list):
        for item in memories[:12]:
            if not isinstance(item, dict):
                result["skipped"] += 1
                continue
            operation = str(item.get("operation", "upsert")).casefold()
            kind = str(item.get("kind", "user_fact")).casefold()
            value = str(item.get("value", "")).strip()
            key = str(item.get("key", "")).strip()
            explicit = _as_bool(item.get("explicitly_stated", False))
            sensitive = _as_bool(item.get("sensitive", False))
            hard_fact = kind in {"world_fact", "hard_fact"}
            metadata: dict[str, Any] = {}
            expires_at: str | None = None

            if operation not in {"upsert", "create", "reinforce", "update"}:
                result["skipped"] += 1
                continue
            if not value or not key:
                result["skipped"] += 1
                continue
            if (kind in PERSONAL_KINDS or sensitive) and not explicit:
                result["skipped"] += 1
                continue
            if hard_fact:
                available_urls = _evidence_urls(grounded_evidence)
                requested_urls = item.get("source_urls", [])
                if not isinstance(requested_urls, list):
                    requested_urls = []
                verified_urls = [
                    str(url).strip()
                    for url in requested_urls[:4]
                    if str(url).strip() in available_urls
                ]
                if not verified_urls:
                    result["skipped"] += 1
                    continue
                try:
                    freshness_days = int(item.get("freshness_days", 30))
                except (TypeError, ValueError):
                    freshness_days = 30
                freshness_days = max(1, min(freshness_days, 3650))
                expires_at = (
                    datetime.now(timezone.utc) + timedelta(days=freshness_days)
                ).replace(microsecond=0).isoformat()
                metadata = {
                    "grounding": "web",
                    "source_urls": verified_urls,
                    "freshness_days": freshness_days,
                }
            try:
                store.upsert_memory(
                    kind=kind,
                    memory_key=key,
                    value=value,
                    source_message_id=source_message_id,
                    confidence=float(item.get("confidence", 0.75)),
                    salience=float(item.get("salience", 0.5)),
                    explicitly_stated=explicit,
                    sensitive=sensitive,
                    expires_at=expires_at,
                    reason=f"model protocol: {operation}",
                    metadata=metadata,
                )
                result["stored"] += 1
            except (ValueError, TypeError):
                result["skipped"] += 1

    session = payload.get("session")
    if isinstance(session, dict):
        updates: dict[str, Any] = {}
        for field in ("title", "summary", "current_task", "tone_state", "active_project"):
            if field in session and isinstance(session[field], (str, int, float)):
                updates[field] = str(session[field])
        for field in ("open_loops", "decisions"):
            if field in session and isinstance(session[field], list):
                updates[field] = session[field]
        if updates:
            store.update_session(session_id, **updates)
            result["session_updated"] = 1
    return result


__all__ = [
    "CLOSE_MARKER",
    "HiddenMemoryFilter",
    "MEMORY_PROTOCOL_INSTRUCTIONS",
    "OPEN_MARKER",
    "apply_memory_payload",
    "parse_memory_payload",
]
